//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Win {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolTipText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTipText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Calculator.Win.ToolTipText", typeof(ToolTipText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 0 (Key:-&gt;  0).
        /// </summary>
        internal static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 1 (Key:-&gt;  1).
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 2 (Key:-&gt;  2).
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 3 (Key:-&gt;  3).
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 4 (Key:-&gt;  4).
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 5 (Key:-&gt;  5).
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 6 (Key:-&gt;  6).
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 7 (Key:-&gt;  7).
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 8 (Key:-&gt;  8).
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number 9 (Key:-&gt;  9).
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Point (Key:-&gt; . ).
        /// </summary>
        internal static string _decimal {
            get {
                return ResourceManager.GetString("decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Clear (ShortcutKey:-&gt;  Shift+A ).
        /// </summary>
        internal static string AC {
            get {
                return ResourceManager.GetString("AC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Ans (ShortcutKey:-&gt;A ).
        /// </summary>
        internal static string Ans {
            get {
                return ResourceManager.GetString("Ans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Backs a Character or Selected Text | (Key:- BackSpace).
        /// </summary>
        internal static string backspace {
            get {
                return ResourceManager.GetString("backspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Brackets|   )   |(Key:-&gt; ) or Shift+0).
        /// </summary>
        internal static string closebrace {
            get {
                return ResourceManager.GetString("closebrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selected otherwise all text.|(ShortCut KEy:-&gt; Ctrl+C).
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoSine value|    Cos(x)    |(Shortcut Key:-&gt;  C ).
        /// </summary>
        internal static string cos {
            get {
                return ResourceManager.GetString("cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CosSineInverse value|   cosi(x)    |(Shortcut Key:-&gt; Shift+C).
        /// </summary>
        internal static string cosi {
            get {
                return ResourceManager.GetString("cosi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cube |    Cube(x)   |(Shortcut Key:-&gt;Shift+3).
        /// </summary>
        internal static string cube {
            get {
                return ResourceManager.GetString("cube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CubeRoot|    ∛(x)     |(Shortcut Key:-&gt; Ctrl+3).
        /// </summary>
        internal static string cuberoot {
            get {
                return ResourceManager.GetString("cuberoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuts the selected otherwise all text.|(ShortCut KEy:-&gt; Ctrl+X).
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division Operator |   a÷b   |  (Key:- &gt;   /).
        /// </summary>
        internal static string divide {
            get {
                return ResourceManager.GetString("divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performs the calculation (Key:-&gt; =,Enter).
        /// </summary>
        internal static string EqualsTo {
            get {
                return ResourceManager.GetString("EqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log(base e)|    Log(x)   |(Shortcut Key:-&gt; Shift+L ).
        /// </summary>
        internal static string ln {
            get {
                return ResourceManager.GetString("ln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log(base10)|    Ln(x)   |(Shortcut Key:-&gt; L).
        /// </summary>
        internal static string log {
            get {
                return ResourceManager.GetString("log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Add (ShortcutKey:-&gt;  Ctrl+W).
        /// </summary>
        internal static string Madd {
            get {
                return ResourceManager.GetString("Madd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Clear (ShortcutKey:-&gt;  Ctrl+D).
        /// </summary>
        internal static string MC {
            get {
                return ResourceManager.GetString("MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substraction(Difference) Operator|    a-b   |  (Key:- &gt;   -).
        /// </summary>
        internal static string minus {
            get {
                return ResourceManager.GetString("minus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Subtract (ShortcutKey:-&gt;  Ctrk+E).
        /// </summary>
        internal static string Mminus {
            get {
                return ResourceManager.GetString("Mminus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remainder when a÷b|   a mod b   |(ShortCut Key:-&gt; M).
        /// </summary>
        internal static string mod {
            get {
                return ResourceManager.GetString("mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Read (ShortcutKey:-&gt;  Ctrl+R).
        /// </summary>
        internal static string MR {
            get {
                return ResourceManager.GetString("MR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Store (ShortcutKey:-&gt;  Ctrl+S).
        /// </summary>
        internal static string MS {
            get {
                return ResourceManager.GetString("MS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication(Product) Operator|   axb    | (Key:- &gt;   *).
        /// </summary>
        internal static string multiply {
            get {
                return ResourceManager.GetString("multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Brackets|   (   |(Key:-&gt; ( or Shift+9).
        /// </summary>
        internal static string openbrace {
            get {
                return ResourceManager.GetString("openbrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastes the copied or cut content.|(ShortCut KEy:-&gt; Ctrl+V).
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage|  x % |(ShortCutKey:-&gt;Shift+5 or %).
        /// </summary>
        internal static string percent {
            get {
                return ResourceManager.GetString("percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition(Sum) Operator|   a+b   |  (Key:- &gt;   +).
        /// </summary>
        internal static string plus {
            get {
                return ResourceManager.GetString("plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a raised to the power b|    a^(b)   |(ShortCut KEy:-&gt; Shift+6 or ^).
        /// </summary>
        internal static string power {
            get {
                return ResourceManager.GetString("power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciprocal |   rcpl(x)   |(ShortCut Key:-&gt; R).
        /// </summary>
        internal static string rcpl {
            get {
                return ResourceManager.GetString("rcpl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n&apos;th root|   n√(x)   |(ShortCut Key:-&gt; Ctrl+1).
        /// </summary>
        internal static string root {
            get {
                return ResourceManager.GetString("root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse the sign|   Sign(x)   |(ShortCut Key:-&gt; Shift+R).
        /// </summary>
        internal static string sign {
            get {
                return ResourceManager.GetString("sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine value|   Sin(x)    |(Shortcut Key:-&gt; S).
        /// </summary>
        internal static string sin {
            get {
                return ResourceManager.GetString("sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SineInverse|   Sini(x)   |(Shortcut Key:-&gt; Shift+S).
        /// </summary>
        internal static string sini {
            get {
                return ResourceManager.GetString("sini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square|   sqr(x)   |(Shortcut Key:-&gt;Shift+2).
        /// </summary>
        internal static string sqr {
            get {
                return ResourceManager.GetString("sqr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SquareRoot|   √(x)   |(Shortcut Key:-&gt;Ctrl+2).
        /// </summary>
        internal static string sqrroot {
            get {
                return ResourceManager.GetString("sqrroot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangent value|   tan(x)   |(Shortcut Key:-&gt; T).
        /// </summary>
        internal static string tan {
            get {
                return ResourceManager.GetString("tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TanInverse value|   tani(x)   |(Shortcut Key:-&gt; Shift+T).
        /// </summary>
        internal static string tani {
            get {
                return ResourceManager.GetString("tani", resourceCulture);
            }
        }
    }
}
